language: python
sudo: false
cache:
  pip: true
  apt: true
python:
  - "2.7"
env:
 - DJANGO=django==1.6.11
 - DJANGO=django
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install $DJANGO
  - pip install .
script:
  - ./run_tests.sh
