language: python
sudo: false
cache:
  pip: true
  apt: true
python:
  - "2.7"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install .
script:
  - python manage.py test
